### PR TITLE
Add Google BigQuery support 

### PR DESCRIPTION
**Pull request by abhi18av**
This PR adds support for the Google BigQuery JDBC interface https://cloud.google.com/bigquery/docs/reference/odbc-jdbc-drivers 

Thanks a ton to @jorgeaguileraseqera on his guidance on Gradle as well as testing for non-core plugins 🙏 💚

### CODE REVIEW

**Review by jorgeaguileraseqera — APPROVED** [review]

**Comment by pditommaso** [comment]
This is super useful, but I think it's time we start to split this project into independent plugin e.g. nf-sqldb for core SQL support i.e. current drivers less Athena, `nf-athena` for AWS Athena, `nf-bigquery` for Google Big query, etc. WDYT?

**Comment by pditommaso** [comment]
I think it's just matter of packaging, the `nf-bigquery` should be a separate plugin that depends on the `nf-sqldb` plugin, therefore everything remains as it is in term of implementation and configuration.

**Comment by abhi18av** [comment]
Mmm, if this is the overall vision for the plugin happy to accommodate any feedback on the restructure.

Regarding the next steps - would this be a different repo? Not sure how the Gradle side of things would need to be updated 🤔

**Comment by pditommaso** [comment]
Yes, it should be `nf-bigquery`, the gradle and project structure should be the usual for plugins. The only change is to include the `nf-sqldb` as a dependency in the gradle submodule, I guess the plugin manifest should declare the dependency with the `nf-sqldb` db

**Review by pditommaso — CHANGES_REQUESTED** [review]
We discussed. The plan is to keep in this project but to move the code in the `plugins/nf-bigquery` source tree

**Review by pditommaso — APPROVED** [review]
Cool

**Comment by abhi18av** [comment]
Opened the PR for review again after 
- [x] The refactor has been completed and @jorgeaguileraseqera confirmed that the publish task can publish both zips
- [x] The integration test is passing for `nf-bigquery` 
- [x] The docs have been updated 

Over to you @pditommaso 😊

**Pull request merged**
